version: '{build}'

image: Visual Studio 2019

environment:
  CONFIGURATION: Release

install:
- git submodule update --init --recursive
- appveyor AddMessage "Change boot configuration and reboot" -Category Information
- bcdedit /set testsigning on
- ps: Start-Sleep -s 5
- ps: Restart-Computer -Force
- ps: Start-Sleep -s 10

build_script:
- appveyor AddMessage "Reboot complete" -Category Information
- bcdedit | findstr /i "testsigning"
- tools\build.bat %CONFIGURATION%
